[env]
PERYX_PLAYWRIGHT_PACKAGE_VERSION = "1.63.0"
PERYX_PLAYWRIGHT_BROWSER_VERSION = "153.0.8010.12"
PERYX_PUPPETEER_PACKAGE_VERSION = "25.10.0"
PERYX_PUPPETEER_BROWSER_VERSION = "152.0.7977.75"

[tools."http:playwright-headless-shell"]
version = "153.0.8010.12"
strip_components = 1

[tools."http:playwright-headless-shell".platforms]
linux-x64 = { url = "https://storage.googleapis.com/chrome-for-testing-public/153.0.8010.12/linux64/chrome-headless-shell-linux64.zip", checksum = "sha256:a9da028861a0cf789ff25c2fed45f5f1aaf969ed9247835b6a7821a4f7af9d1d" }
macos-arm64 = { url = "https://storage.googleapis.com/chrome-for-testing-public/153.0.8010.12/mac-arm64/chrome-headless-shell-mac-arm64.zip", checksum = "sha256:89d80a6d26ccd0ccfd51e22d9e1297283862af2b0cd91dce07459b35ca0059f2" }
macos-x64 = { url = "https://storage.googleapis.com/chrome-for-testing-public/153.0.8010.12/mac-x64/chrome-headless-shell-mac-x64.zip", checksum = "sha256:5c2eaa1aad62111bb5a70dd0889dd3093f3142277b8f78957a238257ee85f009" }
windows-x64 = { url = "https://storage.googleapis.com/chrome-for-testing-public/153.0.8010.12/win64/chrome-headless-shell-win64.zip", checksum = "sha256:7aec872f3090e639c4237467624ea863c20fe2878914c93a6556bdbb52aa6c4c" }

[tools."http:puppeteer-headless-shell"]
version = "152.0.7977.75"
strip_components = 1

[tools."http:puppeteer-headless-shell".platforms]
linux-x64 = { url = "https://storage.googleapis.com/chrome-for-testing-public/152.0.7977.75/linux64/chrome-headless-shell-linux64.zip", checksum = "sha256:66ffefd34dc6af6c7d8e6933546c40ed5278fa3d495c3e836895241ba3a3a19f" }
macos-arm64 = { url = "https://storage.googleapis.com/chrome-for-testing-public/152.0.7977.75/mac-arm64/chrome-headless-shell-mac-arm64.zip", checksum = "sha256:9f599a775de391846eac644b50ed885474e27769ba73096e15507e732e04edef" }
macos-x64 = { url = "https://storage.googleapis.com/chrome-for-testing-public/152.0.7977.75/mac-x64/chrome-headless-shell-mac-x64.zip", checksum = "sha256:667e71c8d261f9cbb4e64639a7691d600f55e88ecc4920a6946c7971be0e67a1" }
windows-x64 = { url = "https://storage.googleapis.com/chrome-for-testing-public/152.0.7977.75/win64/chrome-headless-shell-win64.zip", checksum = "sha256:97bf78fdb5eba45b19ba875e2215cf02813c576780ad406ad7d2a003eef4b956" }
