[env]
PERYX_PLAYWRIGHT_PACKAGE_VERSION = "1.63.0"
PERYX_PLAYWRIGHT_BROWSER_VERSION = "153.0.8010.12"
PERYX_PUPPETEER_PACKAGE_VERSION = "25.12.0"
PERYX_PUPPETEER_BROWSER_VERSION = "154.0.8037.57"

[tools."http:playwright-headless-shell"]
version = "153.0.8010.12"
strip_components = 1

[tools."http:playwright-headless-shell".platforms]
linux-x64 = { url = "https://storage.googleapis.com/chrome-for-testing-public/153.0.8010.12/linux64/chrome-headless-shell-linux64.zip", checksum = "sha256:a9da028861a0cf789ff25c2fed45f5f1aaf969ed9247835b6a7821a4f7af9d1d" }
macos-arm64 = { url = "https://storage.googleapis.com/chrome-for-testing-public/153.0.8010.12/mac-arm64/chrome-headless-shell-mac-arm64.zip", checksum = "sha256:89d80a6d26ccd0ccfd51e22d9e1297283862af2b0cd91dce07459b35ca0059f2" }
macos-x64 = { url = "https://storage.googleapis.com/chrome-for-testing-public/153.0.8010.12/mac-x64/chrome-headless-shell-mac-x64.zip", checksum = "sha256:5c2eaa1aad62111bb5a70dd0889dd3093f3142277b8f78957a238257ee85f009" }
windows-x64 = { url = "https://storage.googleapis.com/chrome-for-testing-public/153.0.8010.12/win64/chrome-headless-shell-win64.zip", checksum = "sha256:7aec872f3090e639c4237467624ea863c20fe2878914c93a6556bdbb52aa6c4c" }

[tools."http:puppeteer-headless-shell"]
version = "154.0.8037.57"
strip_components = 1

[tools."http:puppeteer-headless-shell".platforms]
linux-x64 = { url = "https://storage.googleapis.com/chrome-for-testing-public/154.0.8037.57/linux64/chrome-headless-shell-linux64.zip", checksum = "sha256:5a6979d0ab7cf952ea575d35164e7bdce4872b2ced8f8a215c8f8e8eda00ee09" }
macos-arm64 = { url = "https://storage.googleapis.com/chrome-for-testing-public/154.0.8037.57/mac-arm64/chrome-headless-shell-mac-arm64.zip", checksum = "sha256:9ba4d8a9732bd7e431ce9009d1bbe1ccf7f8c5de2a9781054f500a9fe898124d" }
macos-x64 = { url = "https://storage.googleapis.com/chrome-for-testing-public/154.0.8037.57/mac-x64/chrome-headless-shell-mac-x64.zip", checksum = "sha256:b3f9551d90c9ff0f4c7c231a4dbf226b3c64faba8ced1ab61a5ef9d430d0e996" }
windows-x64 = { url = "https://storage.googleapis.com/chrome-for-testing-public/154.0.8037.57/win64/chrome-headless-shell-win64.zip", checksum = "sha256:bcc91b4d0f83a5457fc6ca7941fd65f2349775523d961be88526c6a66560dc75" }
