[tools]
zola = "latest"
node = "22.23.2"
uv = "latest"
prek = "latest"
cargo-binstall = "latest"
just = "latest"
jq = "latest"
"cargo:cargo-auditable" = "latest"
"cargo:cargo-cyclonedx" = "latest"
"cargo:cargo-codspeed" = "latest"
"cargo:cargo-deny" = "latest"
"cargo:cargo-dist" = "latest"
"cargo:cargo-fuzz" = "latest"
"cargo:cargo-hack" = "latest"
"cargo:cargo-insta" = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:cargo-llvm-cov" = "latest"
"cargo:cargo-mutants" = "latest"
"cargo:cargo-semver-checks" = "latest"
"cargo:maturin" = "latest"
"github:leptos-rs/cargo-leptos" = "latest"
"github:Shopify/toxiproxy" = { version = "2.12.0", matching = "toxiproxy-server", bin = "toxiproxy-server", github_attestations = false }
