[tools]
zola = "latest"
node = "22"
uv = "latest"
prek = "latest"
cargo-binstall = "latest"
just = "latest"
jq = "latest"
shellcheck = "latest"
"cargo:cargo-auditable" = "latest"
"cargo:cargo-cyclonedx" = "latest"
"cargo:cargo-deny" = "latest"
"cargo:cargo-dist" = "latest"
"cargo:cargo-fuzz" = "latest"
"cargo:cargo-hack" = "latest"
"cargo:cargo-hawk" = "latest"
"cargo:cargo-insta" = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:cargo-llvm-cov" = "latest"
"cargo:cargo-mutants" = "latest"
"cargo:cargo-semver-checks" = "latest"
"cargo:cargo-shear" = "latest"
"cargo:maturin" = "latest"
"ubi:leptos-rs/cargo-leptos" = { version = "latest", exe = "cargo-leptos" }
