[env]
PERYX_PLAYWRIGHT_PACKAGE_VERSION = "1.63.0"
PERYX_PLAYWRIGHT_BROWSER_VERSION = "153.0.8010.12"
PERYX_PUPPETEER_PACKAGE_VERSION = "25.11.0"
PERYX_PUPPETEER_BROWSER_VERSION = "153.0.8010.36"

[tools."http:playwright-headless-shell"]
version = "153.0.8010.12"
strip_components = 1

[tools."http:playwright-headless-shell".platforms]
linux-x64 = { url = "https://storage.googleapis.com/chrome-for-testing-public/153.0.8010.12/linux64/chrome-headless-shell-linux64.zip", checksum = "sha256:a9da028861a0cf789ff25c2fed45f5f1aaf969ed9247835b6a7821a4f7af9d1d" }
macos-arm64 = { url = "https://storage.googleapis.com/chrome-for-testing-public/153.0.8010.12/mac-arm64/chrome-headless-shell-mac-arm64.zip", checksum = "sha256:89d80a6d26ccd0ccfd51e22d9e1297283862af2b0cd91dce07459b35ca0059f2" }
macos-x64 = { url = "https://storage.googleapis.com/chrome-for-testing-public/153.0.8010.12/mac-x64/chrome-headless-shell-mac-x64.zip", checksum = "sha256:5c2eaa1aad62111bb5a70dd0889dd3093f3142277b8f78957a238257ee85f009" }
windows-x64 = { url = "https://storage.googleapis.com/chrome-for-testing-public/153.0.8010.12/win64/chrome-headless-shell-win64.zip", checksum = "sha256:7aec872f3090e639c4237467624ea863c20fe2878914c93a6556bdbb52aa6c4c" }

[tools."http:puppeteer-headless-shell"]
version = "153.0.8010.36"
strip_components = 1

[tools."http:puppeteer-headless-shell".platforms]
linux-x64 = { url = "https://storage.googleapis.com/chrome-for-testing-public/153.0.8010.36/linux64/chrome-headless-shell-linux64.zip", checksum = "sha256:a0079df5617da34bcd1debad18196568b072ec3d8ec57944008972a4fc970580" }
macos-arm64 = { url = "https://storage.googleapis.com/chrome-for-testing-public/153.0.8010.36/mac-arm64/chrome-headless-shell-mac-arm64.zip", checksum = "sha256:3b133378fe44a5f9c849df9049763577fbed296ee4d02d1ffb31b9fcabf79850" }
macos-x64 = { url = "https://storage.googleapis.com/chrome-for-testing-public/153.0.8010.36/mac-x64/chrome-headless-shell-mac-x64.zip", checksum = "sha256:d2ab9d1cd671137283dd5dd76ad91df82c686ff3d4c0150c9c72aa0463a59037" }
windows-x64 = { url = "https://storage.googleapis.com/chrome-for-testing-public/153.0.8010.36/win64/chrome-headless-shell-win64.zip", checksum = "sha256:dc59aeda4f9ce8a9a329693617ac5d8b75ceea52ac3d794c4af06cdee261040e" }
