[package]
name = "peryx-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Content-addressed blob store and metadata storage for peryx."

[dependencies]
atomicwrites.workspace = true
aws-config.workspace = true
aws-sdk-s3.workspace = true
base64.workspace = true
bytes.workspace = true
futures-util.workspace = true
fs4.workspace = true
hex.workspace = true
peryx-identity.workspace = true
peryx-policy.workspace = true
sha2.workspace = true
thiserror.workspace = true
tempfile.workspace = true
tokio.workspace = true
uuid.workspace = true
redb.workspace = true
serde.workspace = true
serde_json.workspace = true
flate2.workspace = true
tar.workspace = true
zip.workspace = true
tracing.workspace = true
url.workspace = true

[dev-dependencies]
aws-smithy-http-client.workspace = true
http.workspace = true
http-body.workspace = true
http-body-util.workspace = true
mockall.workspace = true
reqwest.workspace = true
rstest.workspace = true
testcontainers.workspace = true
testcontainers-modules.workspace = true
wiremock.workspace = true

[lints]
workspace = true
