//! The neutral artifact source and byte-availability projection.
//!
//! Two orthogonal dimensions describe an artifact independent of any ecosystem. Its [`ArtifactSource`]
//! records where the bytes came from and is intrinsic: caching or evicting them never changes it. Its
//! [`ByteAvailability`] projects whether this instance can serve the bytes right now, and is a
//! projection maintained across publish, cache fill, eviction, failed fetch, and storage repair.
//!
//! Policy, yank, trash, and revocation are separate dimensions this module never reads or writes; a
//! repair pass reconciles availability against stored bytes without touching any of them.

use std::ops::Bound::{Excluded, Unbounded};

use redb::{ReadableTable as _, ReadableTableMetadata as _};
use serde::{Deserialize, Serialize};

use super::{ARTIFACT_PLACEMENT, MetaError, MetaStore};

/// The largest batch [`MetaStore::repair_artifact_placements`] reconciles in one call, so a repair
/// pass stays bounded and never holds a read span over the whole table.
pub const MAX_REPAIR_BATCH: usize = 1_000;

/// The largest page [`MetaStore::list_artifact_placements`] returns, bounding a placement-health view's
/// per-request work so it never scales with the object count.
const MAX_QUERY_LIMIT: usize = 100;

/// Where an artifact's bytes came from. Persisted and intrinsic: it does not change when the bytes are
/// cached or evicted, only when a different artifact takes the digest's place.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ArtifactSource {
    /// Published into this instance. No upstream can resupply the bytes once they are lost.
    Hosted,
    /// Cached from an upstream index. A local miss can be answered by re-fetching from upstream.
    Proxy,
    /// Produced by this instance, such as a rendered index page or a derived metadata sibling. A local
    /// miss is answered by regenerating, not by an upstream fetch.
    Generated,
}

impl ArtifactSource {
    /// The stable wire spelling, matching the `snake_case` serde form.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Hosted => "hosted",
            Self::Proxy => "proxy",
            Self::Generated => "generated",
        }
    }

    /// Whether an upstream can resupply this artifact's bytes after a local miss. Only a proxied
    /// artifact has one; hosted and generated bytes have no remote to fall back to.
    #[must_use]
    pub const fn has_upstream(self) -> bool {
        matches!(self, Self::Proxy)
    }

    /// The availability an artifact of this source projects when its verified bytes are not local: a
    /// proxied artifact stays reachable upstream, everything else becomes unavailable.
    #[must_use]
    const fn without_bytes(self) -> ByteAvailability {
        if self.has_upstream() {
            ByteAvailability::RemoteOnly
        } else {
            ByteAvailability::Unavailable
        }
    }
}

/// Whether this instance can serve an artifact's bytes right now. A projection, kept in step with the
/// content store by the events below; a package read consults it without a per-artifact backend probe.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ByteAvailability {
    /// The configured storage holds verified bytes; a read serves them without an upstream fetch.
    Local,
    /// No local bytes, but a known upstream can supply them.
    RemoteOnly,
    /// No local bytes and no upstream to supply them.
    Unavailable,
}

impl ByteAvailability {
    /// The stable wire spelling, matching the `snake_case` serde form.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Local => "local",
            Self::RemoteOnly => "remote_only",
            Self::Unavailable => "unavailable",
        }
    }

    /// Whether the bytes can be served from local storage without an upstream fetch.
    #[must_use]
    pub const fn is_local(self) -> bool {
        matches!(self, Self::Local)
    }
}

/// A change to an artifact's local bytes that reprojects its [`ByteAvailability`].
///
/// The source never changes; only availability moves. [`Self::WriteFailed`] is the one event that
/// keeps the prior state rather than deriving a new one, so a failed cache fill can neither drop a
/// previously verified local copy nor fabricate one from a partial transfer.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PlacementEvent {
    /// Verified, complete bytes were written: a publish, a generate, or a completed cache fill. The
    /// caller must have verified the digest first; metadata alone or a partial transfer must not emit
    /// this.
    BytesVerified,
    /// A write or cache fill did not produce verified bytes. Local bytes are left exactly as they were.
    WriteFailed,
    /// Local bytes were removed: an eviction, or a repair that dropped a corrupt blob.
    BytesRemoved,
    /// A repair pass observed whether verified bytes are currently present.
    Repaired { present: bool },
}

/// An artifact's neutral placement: its persisted source and projected byte availability.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct ArtifactPlacement {
    pub source: ArtifactSource,
    pub availability: ByteAvailability,
}

impl ArtifactPlacement {
    /// The placement of a freshly recorded artifact of `source` whose verified bytes are `present`.
    #[must_use]
    pub const fn record(source: ArtifactSource, present: bool) -> Self {
        Self {
            source,
            availability: Self::project(source, present),
        }
    }

    /// Availability derived from byte presence: present verified bytes are [`ByteAvailability::Local`],
    /// otherwise the source decides between remote-only and unavailable.
    const fn project(source: ArtifactSource, present: bool) -> ByteAvailability {
        if present {
            ByteAvailability::Local
        } else {
            source.without_bytes()
        }
    }

    /// Reproject after `event`, keeping the intrinsic source.
    #[must_use]
    pub const fn after(self, event: PlacementEvent) -> Self {
        let availability = match event {
            PlacementEvent::BytesVerified => ByteAvailability::Local,
            PlacementEvent::BytesRemoved => self.source.without_bytes(),
            PlacementEvent::WriteFailed => self.availability,
            PlacementEvent::Repaired { present } => Self::project(self.source, present),
        };
        Self { availability, ..self }
    }
}

/// Maps one ecosystem's artifact into the neutral [`ArtifactSource`].
///
/// Implemented once per ecosystem so neutral code never matches on ecosystem to decide where an
/// artifact came from: the ecosystem crate owns the mapping, the store owns the projection.
pub trait ArtifactOrigin {
    /// The neutral source this artifact records under.
    fn artifact_source(&self) -> ArtifactSource;
}

/// One row of a placement listing: a digest and its neutral source and byte availability, the shape a
/// placement-health view reads without exposing internal file paths or tenant data.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct ArtifactPlacementRow {
    pub digest: String,
    pub source: ArtifactSource,
    pub availability: ByteAvailability,
}

/// A bounded, cursor-paginated query over artifact placements in digest order.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ArtifactPlacementQuery {
    /// Resume after this digest, exclusive; `None` starts at the first.
    pub cursor: Option<String>,
    pub limit: usize,
}

impl Default for ArtifactPlacementQuery {
    fn default() -> Self {
        Self {
            cursor: None,
            limit: 25,
        }
    }
}

/// One bounded page of placement rows in digest order, with a cursor to resume.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct ArtifactPlacementPage {
    pub rows: Vec<ArtifactPlacementRow>,
    /// The digest to resume after, present only when more rows remain past this page.
    pub next_cursor: Option<String>,
}

/// The counts a placement-health view shows.
///
/// How many artifacts serve locally, how many are reachable only upstream, and how many cannot be served
/// at all: three numbers regardless of table size, so the aggregate stays bounded output even when the
/// table it summarizes is not.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize)]
pub struct ArtifactPlacementHealth {
    pub local: u64,
    pub remote_only: u64,
    pub unavailable: u64,
}

impl ArtifactPlacementHealth {
    /// The total placements across the three availability states.
    #[must_use]
    pub const fn total(self) -> u64 {
        self.local + self.remote_only + self.unavailable
    }
}

/// A rejected placement list.
#[derive(Debug, thiserror::Error)]
pub enum ArtifactPlacementQueryError {
    #[error(transparent)]
    Store(#[from] MetaError),
    #[error("limit must be between 1 and {MAX_QUERY_LIMIT}")]
    InvalidLimit,
}

/// The outcome of one bounded [`MetaStore::repair_artifact_placements`] pass.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PlacementRepairPage {
    /// How many placement rows the pass read.
    pub scanned: usize,
    /// How many rows had a stale availability the pass rewrote.
    pub reconciled: usize,
    /// The digest to resume after, or `None` when the pass reached the end of the table.
    pub next_cursor: Option<String>,
}

impl MetaStore {
    /// Persist an artifact's placement, keyed by its content digest.
    ///
    /// # Errors
    /// Returns a store error if the write fails.
    pub fn put_artifact_placement(&self, digest: &str, placement: &ArtifactPlacement) -> Result<(), MetaError> {
        let encoded = serde_json::to_vec(placement)?;
        let txn = self.db.begin_write()?;
        {
            let mut table = txn.open_table(ARTIFACT_PLACEMENT)?;
            table.insert(digest, encoded.as_slice())?;
        }
        txn.commit()?;
        Ok(())
    }

    /// Read one artifact's placement with a single indexed lookup, without probing the content store.
    ///
    /// # Errors
    /// Returns a store error if the read or decode fails.
    pub fn get_artifact_placement(&self, digest: &str) -> Result<Option<ArtifactPlacement>, MetaError> {
        let txn = self.db.begin_read()?;
        let table = txn.open_table(ARTIFACT_PLACEMENT)?;
        Ok(table
            .get(digest)?
            .map(|value| serde_json::from_slice(value.value()))
            .transpose()?)
    }

    /// Count persisted artifact placements: the size of the availability projection a backup records
    /// and a verifier re-derives to catch a metadata copy taken at a different recovery point.
    ///
    /// # Errors
    /// Returns a store error if the table cannot be read.
    pub fn count_artifact_placements(&self) -> Result<u64, MetaError> {
        let txn = self.db.begin_read()?;
        let table = txn.open_table(ARTIFACT_PLACEMENT)?;
        Ok(table.len()?)
    }

    /// List artifact placements in digest order with an exclusive cursor, giving a placement-health view
    /// a bounded data source of per-digest `{digest, source, availability}` rows.
    ///
    /// Reads one row past `limit` to decide whether more remain: a full page carries a `next_cursor`
    /// pointing at its last digest, and a page that reaches the end carries none. The read span is
    /// bounded by the validated limit, so a large table never turns into one unbounded scan.
    ///
    /// # Errors
    /// Returns [`ArtifactPlacementQueryError::InvalidLimit`] for a limit outside `1..=MAX_QUERY_LIMIT`,
    /// or a store error when a row cannot be read or decoded.
    pub fn list_artifact_placements(
        &self,
        query: &ArtifactPlacementQuery,
    ) -> Result<ArtifactPlacementPage, ArtifactPlacementQueryError> {
        if !(1..=MAX_QUERY_LIMIT).contains(&query.limit) {
            return Err(ArtifactPlacementQueryError::InvalidLimit);
        }
        let txn = self.db.begin_read().map_err(MetaError::from)?;
        let table = txn.open_table(ARTIFACT_PLACEMENT).map_err(MetaError::from)?;
        let entries = query
            .cursor
            .as_ref()
            .map_or_else(
                || table.iter(),
                |cursor| table.range::<&str>((Excluded(cursor.as_str()), Unbounded)),
            )
            .map_err(MetaError::from)?;
        let mut rows = Vec::with_capacity(query.limit + 1);
        for entry in entries {
            let (key, value) = entry.map_err(MetaError::from)?;
            let placement: ArtifactPlacement = serde_json::from_slice(value.value()).map_err(MetaError::from)?;
            rows.push(ArtifactPlacementRow {
                digest: key.value().to_owned(),
                source: placement.source,
                availability: placement.availability,
            });
            if rows.len() > query.limit {
                break;
            }
        }
        let next_cursor = (rows.len() > query.limit).then(|| rows[query.limit - 1].digest.clone());
        rows.truncate(query.limit);
        Ok(ArtifactPlacementPage { rows, next_cursor })
    }

    /// Bucket every artifact placement by byte availability in one read pass, giving a placement-health
    /// view its aggregate without paging the whole table itself. The output is three counts regardless of
    /// table size, so the summary aggregates before serialization; the read scans the placement table once
    /// off the request path's paged reads.
    ///
    /// # Errors
    /// Returns a store error if a row cannot be read or decoded.
    pub fn artifact_placement_health(&self) -> Result<ArtifactPlacementHealth, MetaError> {
        let txn = self.db.begin_read()?;
        let table = txn.open_table(ARTIFACT_PLACEMENT)?;
        let mut health = ArtifactPlacementHealth::default();
        for entry in table.iter()? {
            let (_key, value) = entry?;
            let placement: ArtifactPlacement = serde_json::from_slice(value.value())?;
            match placement.availability {
                ByteAvailability::Local => health.local += 1,
                ByteAvailability::RemoteOnly => health.remote_only += 1,
                ByteAvailability::Unavailable => health.unavailable += 1,
            }
        }
        Ok(health)
    }

    /// Record a newly seen artifact of `source` whose verified bytes are `present`, replacing any prior
    /// placement for the digest, and return the stored value.
    ///
    /// # Errors
    /// Returns a store error if the write fails.
    pub fn record_artifact_placement(
        &self,
        digest: &str,
        source: ArtifactSource,
        present: bool,
    ) -> Result<ArtifactPlacement, MetaError> {
        let placement = ArtifactPlacement::record(source, present);
        self.put_artifact_placement(digest, &placement)?;
        Ok(placement)
    }

    /// Record a discovered artifact of `source` whose bytes are not yet local, but only when the digest
    /// has no placement yet, and return the stored value. A re-discovery of an already-cached artifact
    /// keeps its [`ByteAvailability::Local`] state rather than resetting it to remote-only.
    ///
    /// # Errors
    /// Returns a store error if the row cannot be read, encoded, or committed.
    pub fn ensure_artifact_placement(
        &self,
        digest: &str,
        source: ArtifactSource,
    ) -> Result<ArtifactPlacement, MetaError> {
        let txn = self.db.begin_write()?;
        let placement = {
            let mut table = txn.open_table(ARTIFACT_PLACEMENT)?;
            let existing = table
                .get(digest)?
                .map(|value| serde_json::from_slice::<ArtifactPlacement>(value.value()))
                .transpose()?;
            if let Some(existing) = existing {
                existing
            } else {
                let created = ArtifactPlacement::record(source, false);
                table.insert(digest, serde_json::to_vec(&created)?.as_slice())?;
                created
            }
        };
        txn.commit()?;
        Ok(placement)
    }

    /// Reproject an existing placement after `event` in one transaction, returning the new value or
    /// `None` when no placement was recorded for the digest.
    ///
    /// # Errors
    /// Returns a store error if the row cannot be read, encoded, or committed.
    pub fn apply_placement_event(
        &self,
        digest: &str,
        event: PlacementEvent,
    ) -> Result<Option<ArtifactPlacement>, MetaError> {
        let txn = self.db.begin_write()?;
        let updated = {
            let mut table = txn.open_table(ARTIFACT_PLACEMENT)?;
            let Some(current) = table
                .get(digest)?
                .map(|value| serde_json::from_slice::<ArtifactPlacement>(value.value()))
                .transpose()?
            else {
                return Ok(None);
            };
            let updated = current.after(event);
            if updated != current {
                let encoded = serde_json::to_vec(&updated)?;
                table.insert(digest, encoded.as_slice())?;
            }
            updated
        };
        txn.commit()?;
        Ok(Some(updated))
    }

    /// Remove an artifact's placement, reporting whether it was present.
    ///
    /// # Errors
    /// Returns a store error if the write fails.
    pub fn delete_artifact_placement(&self, digest: &str) -> Result<bool, MetaError> {
        let txn = self.db.begin_write()?;
        let removed = {
            let mut table = txn.open_table(ARTIFACT_PLACEMENT)?;
            table.remove(digest)?.is_some()
        };
        txn.commit()?;
        Ok(removed)
    }

    /// Reconcile a bounded batch of placement projections against actual byte presence.
    ///
    /// Starting after `cursor` in digest order, up to `limit` rows are read; `present` reports whether
    /// each digest's verified bytes are in the content store, and any row whose projection disagrees is
    /// rewritten. Only the availability projection changes: source stays intrinsic and policy, yank,
    /// trash, and revocation are never touched. The returned cursor resumes the next batch, so a
    /// caller drives repair in fixed steps off the request path.
    ///
    /// # Errors
    /// Returns a store error if a row cannot be read, encoded, or committed.
    pub fn repair_artifact_placements(
        &self,
        cursor: Option<&str>,
        limit: usize,
        mut present: impl FnMut(&str) -> bool,
    ) -> Result<PlacementRepairPage, MetaError> {
        let batch = limit.min(MAX_REPAIR_BATCH);
        let txn = self.db.begin_write()?;
        let mut scanned = 0;
        let mut reconciled = 0;
        let mut next_cursor = None;
        {
            let mut table = txn.open_table(ARTIFACT_PLACEMENT)?;
            let pending = collect_repairs(&table, cursor, batch, &mut present, &mut scanned, &mut next_cursor)?;
            for (digest, placement) in pending {
                let encoded = serde_json::to_vec(&placement)?;
                table.insert(digest.as_str(), encoded.as_slice())?;
                reconciled += 1;
            }
        }
        txn.commit()?;
        Ok(PlacementRepairPage {
            scanned,
            reconciled,
            next_cursor,
        })
    }
}

/// Read a bounded batch of placement rows after `cursor`, reprojecting each against `present`, and
/// return the digests whose projection changed. Iteration advances `scanned` and records the last
/// digest read in `next_cursor` when the batch fills, so the caller commits the changes and resumes.
fn collect_repairs(
    table: &redb::Table<'_, &'static str, &'static [u8]>,
    cursor: Option<&str>,
    batch: usize,
    present: &mut impl FnMut(&str) -> bool,
    scanned: &mut usize,
    next_cursor: &mut Option<String>,
) -> Result<Vec<(String, ArtifactPlacement)>, MetaError> {
    if batch == 0 {
        return Ok(Vec::new());
    }
    let entries = match cursor {
        Some(cursor) => table.range::<&str>((Excluded(cursor), Unbounded))?,
        None => table.iter()?,
    };
    let mut pending = Vec::new();
    for entry in entries {
        let (key, value) = entry?;
        let digest = key.value().to_owned();
        let current: ArtifactPlacement = serde_json::from_slice(value.value())?;
        *scanned += 1;
        let repaired = current.after(PlacementEvent::Repaired {
            present: present(&digest),
        });
        if repaired != current {
            pending.push((digest.clone(), repaired));
        }
        if *scanned == batch {
            *next_cursor = Some(digest);
            break;
        }
    }
    Ok(pending)
}

#[cfg(test)]
#[path = "../../tests/unit/meta/placement/tests.rs"]
mod tests;
