#!/usr/bin/env bash
set -euo pipefail

git config --global --add safe.directory "$(pwd)"
git ls-files -s -- \
    .cargo \
    .github/codspeed \
    .github/workflows/codspeed.yml \
    ci/run-codspeed.sh \
    crates \
    Cargo.lock \
    Cargo.toml \
    rust-toolchain.toml \
    | sha256sum \
    | cut -d ' ' -f 1
