pub use peryx_core::{
    UiArtifactRef, UiArtifactSource, UiAttestation, UiByteAvailability, UiFile, UiManifest, UiMember, UiMemberChunk,
    UiProject, UiProjectStatus, UiProjectView, UiProvenance, UiProvenanceSource, UiRelease, UiSubjectMatch,
};

use super::string_at;

/// One placement chip's parts: a stable css key, the visible word, and a longer hint.
///
/// A sighted reader sees the word; a pointer or screen reader gets the hint. The visible word alone
/// distinguishes each state, so the chips never lean on colour.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PlacementLabel {
    pub key: &'static str,
    pub text: &'static str,
    pub hint: &'static str,
}

/// How a file's #441 source renders: where its bytes came from, intrinsic to the artifact.
#[must_use]
pub const fn file_source_label(source: UiArtifactSource) -> PlacementLabel {
    match source {
        UiArtifactSource::Hosted => PlacementLabel {
            key: "hosted",
            text: "hosted",
            hint: "Published into this instance",
        },
        UiArtifactSource::Proxy => PlacementLabel {
            key: "proxy",
            text: "proxy",
            hint: "Cached from an upstream index",
        },
        UiArtifactSource::Generated => PlacementLabel {
            key: "generated",
            text: "generated",
            hint: "Generated by this instance",
        },
    }
}

/// How a file's #441 byte availability renders: whether this instance can serve the bytes now.
#[must_use]
pub const fn byte_availability_label(availability: UiByteAvailability) -> PlacementLabel {
    match availability {
        UiByteAvailability::Local => PlacementLabel {
            key: "local",
            text: "local",
            hint: "Served from local storage",
        },
        UiByteAvailability::RemoteOnly => PlacementLabel {
            key: "remote-only",
            text: "remote-only",
            hint: "Not stored locally; available from the upstream",
        },
        UiByteAvailability::Unavailable => PlacementLabel {
            key: "unavailable",
            text: "unavailable",
            hint: "Not stored locally and no upstream to supply it",
        },
    }
}

/// How an artifact's provenance source renders: whether peryx holds the document or only relays
/// an upstream claim.
#[must_use]
pub const fn provenance_source_label(source: UiProvenanceSource) -> PlacementLabel {
    match source {
        UiProvenanceSource::Hosted => PlacementLabel {
            key: "hosted",
            text: "hosted",
            hint: "Uploaded here; peryx bound each attestation to this distribution at upload",
        },
        UiProvenanceSource::Mirrored => PlacementLabel {
            key: "mirrored",
            text: "mirrored",
            hint: "Advertised by an upstream index; peryx relays the claim without reading it",
        },
    }
}

/// How an attestation's subject binding renders. peryx checks the binding, never the signature, so a
/// match says the bundle was issued for this file, not that it is trustworthy.
#[must_use]
pub const fn subject_match_label(subject: UiSubjectMatch) -> PlacementLabel {
    match subject {
        UiSubjectMatch::Matched => PlacementLabel {
            key: "matched",
            text: "subject matched",
            hint: "An attestation subject names this file's digest",
        },
        UiSubjectMatch::Mismatched => PlacementLabel {
            key: "mismatched",
            text: "subject mismatch",
            hint: "No attestation subject binds this file's digest",
        },
        UiSubjectMatch::Unknown => PlacementLabel {
            key: "unknown",
            text: "subject unknown",
            hint: "The statement carried no readable subject to compare",
        },
    }
}

/// The one-line validation result the panel states for a file's provenance.
///
/// Derived from how peryx obtained the document and whether it could read it. peryx never verifies a
/// Sigstore signature, so the result reports what peryx checked, not that any attestation is genuine.
#[must_use]
pub const fn provenance_validation_label(source: UiProvenanceSource, malformed: bool) -> PlacementLabel {
    match (source, malformed) {
        (UiProvenanceSource::Hosted, false) => PlacementLabel {
            key: "verified-binding",
            text: "binding verified",
            hint: "peryx enforced the subject binding at upload; Sigstore signatures are not checked",
        },
        (UiProvenanceSource::Hosted, true) => PlacementLabel {
            key: "unreadable",
            text: "unreadable",
            hint: "Provenance is present but its stored document could not be read",
        },
        (UiProvenanceSource::Mirrored, _) => PlacementLabel {
            key: "unverified",
            text: "unverified claim",
            hint: "Upstream advertises provenance; peryx neither fetched nor verified it",
        },
    }
}

/// Rebuild an archive listing from the inspect endpoint's JSON document.
#[must_use]
pub fn members_from_listing(value: &serde_json::Value) -> Vec<UiMember> {
    value["members"]
        .as_array()
        .into_iter()
        .flatten()
        .map(|member| UiMember {
            path: string_at(member, "path"),
            size: member["size"].as_u64().unwrap_or_default(),
            kind: member["kind"].as_str().unwrap_or("unknown").to_owned(),
            previewable: member["previewable"].as_bool().unwrap_or(false),
        })
        .collect()
}

/// The project names supplied by one index.
#[must_use]
pub fn projects_from_list(value: &serde_json::Value) -> Vec<String> {
    value["projects"]
        .as_array()
        .into_iter()
        .flatten()
        .map(|project| string_at(project, "name"))
        .collect()
}
