[package]
name = "peryx-oci-system-tests"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
peryx = { path = "../../../peryx", version = "0.0.1", default-features = false, features = ["composition-oci"] }

[dev-dependencies]
axum.workspace = true
base64.workspace = true
flate2.workspace = true
http-body-util.workspace = true
peryx-driver.workspace = true
peryx-ecosystem-oci.workspace = true
peryx-identity.workspace = true
peryx-policy.workspace = true
peryx-storage.workspace = true
peryx-test-support.workspace = true
reqwest = { workspace = true, features = ["blocking", "gzip", "http2", "json", "rustls-no-provider", "stream"] }
rstest.workspace = true
serde_json.workspace = true
tar.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync"] }
toml.workspace = true
tower = { workspace = true, features = ["util"] }

[lints]
workspace = true
